=== AlainBartmanDilaw/oradew-vscode/resources/oradewrc-schema.json
{
  "title": "JSON schema for Oradew configuration file",
  "$schema": "http://json-schema.org/draft-06/schema#",
  "type": "object",
  "properties": {
    "package.input": {
      "default": [
        "./scripts/**/initial*.sql",
        "./src/**/VIEWS/*.sql",
        "./src/**/TYPES/*.sql",
        "./src/**/TYPE_BODIES/*.sql",
        "./src/**/TRIGGERS/*.sql",
        "./src/**/PACKAGES/*.sql",
        "./src/**/PACKAGE_BODIES/*.sql",
        "./src/**/FUNCTIONS/*.sql",
        "./src/**/PROCEDURES/*.sql",
        "./scripts/**/final*.sql",
        "!./**/*EXCLUDE*.sql"
      ],
      "description":
        "Glob pattern for packaging files into deploy script file. \nPreserving order, prefix with ! for excluding.",
      "type": "array"
    },
    "package.output": {
      "default": "./deploy/Run.sql",
      "description": "Deploy package output file.",
      "type": "string"
    },
    "package.encoding": {
      "default": "utf8",
      "description": "Deploy file encoding. \n(utf8, win1250, ...)",
      "type": "string"
    },
    "package.templating": {
      "default": false,
      "description":
        "Package templating of config variables in sql files. \nex.usage in sql code: '${config[\"version.number\"]}'",
      "type": "boolean"
    },
    "source": {
      "default": ["./src/**/*.sql"],
      "description": "Glob pattern for source files.",
      "type": "array"
    },
    "compile.warnings": {
      "default": "NONE",
      "description": "Compilation warning scopes.",
      "type": "string",
      "enum": ["NONE", "ALL", "PERFORMANCE", "INFORMATIONAL", "SEVERE"]
    },
    "compile.force": {
      "default": false,
      "description":
        "Ignore conflict detection and auto-merge of local file changes with DB object when compiling to DEV environment. \nCompilation on other env's is always done with force.",
      "type": "boolean"
    },
    "version.number": {
      "default": "develop",
      "description": "Version number.",
      "type": "string"
    },
    "version.description": {
      "default": "develop",
      "description": "Version description.",
      "type": "string"
    },
    "version.releaseDate": {
      "default": "1899-01-01",
      "description": "Version release date.",
      "type": "string",
      "format": "date-time"
    },
    "test.input": {
      "default": ["./test/**/*.test.sql"],
      "description": "Glob pattern for tests.",
      "type": "array"
    }
  }
}

=== AlainBartmanDilaw/oradew-vscode/test/oradewrc.json
{
  "package.input": [
    ".\\scripts\\initial*.sql",
    ".\\src\\VIEWS\\*.sql",
    ".\\src\\PACKAGES\\*.sql",
    ".\\src\\PACKAGE_BODIES\\*.sql",
    ".\\src\\FUNCTIONS\\*.sql",
    ".\\src\\PROCEDURES\\*.sql",
    ".\\src\\TRIGGERS\\*.sql",
    ".\\scripts\\final*.sql",
    "!.\\**\\*EXCLUDE*.sql"
  ],
  "package.output": ".\\deploy\\Run.sql",
  "package.encoding": "utf8",
  "package.templating": false,
  "source": [
    ".\\src\\**\\*.sql"
  ],
  "compile.warnings": "NONE",
  "compile.force": false,
  "version.number": "develop",
  "version.description": "develop",
  "version.releaseDate": "1899-01-01",
  "test.input": [
    ".\\test\\**\\*.test.sql"
  ]
}
